project:
  type: book
  output-dir: docs

book:
  title: "DRAFT Data in Animal Welfare"
  author: "Jill R D MacKay"
  date: "05/11/2025"
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 02_datatypes.qmd
    - 03_datavis.qmd
    - summary.qmd
    - backmatter.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: pulse
    code-copy: true
  pdf:
    documentclass: scrreprt



